[package]
name = "tm"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scuttle = { git = "https://github.com/Zolmok/scuttle", tag="v0.4.0" }
